# Generated by Django 3.0 on 2020-12-21 11:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_myuser_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to=accounts.models.upload_image_path),
        ),
    ]
