# Generated by Django 3.0 on 2021-01-09 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_users',
            field=models.ManyToManyField(related_name='shared_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_files', to='products.Product'),
        ),
    ]
